version: '3.8'

services:
  nginx:
    build: .
    container_name: my_portfolio
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - myletsencryptcert:/etc/letsencrypt
      - ./portfolio /sr/share/nginx/html # Ensure your HTML files are in the current directory
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - myletsencryptcert:/etc/letsencrypt
      - ./html:/usr/share/nginx/html
    entrypoint: >
      sh -c "certbot certonly --webroot -w /usr/share/nginx/html
      --email tonemail@example.com --agree-tos --no-eff-email
      -d yannoportfolio.com"

volumes:
  myletsencryptcert: